/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package scheduler;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.scheduling.annotation.EnableScheduling;

@SpringBootApplication
@EnableScheduling
public class App {
    public static void main(String[] args) {
        System.out.println("Start");
        SpringApplication.run(App.class, args);
    }
}
